CREATE TABLE `HealthPort`.`ALLERGYINTOLERANCE` (
  `ID` VARCHAR(45) NOT NULL,
  `SUBJECT` TEXT NULL,
  `SUBST_DISPLAY` TEXT NULL,
  `SUBST_CODE` TEXT NULL,
  `SUBST_SYSTEM` TEXT NULL,
  `SENSITIVITY_TYPE` TEXT NULL,
  `RECORDED_DATE` DATE NULL,
  `REACTION` TEXT NULL,
  `CRITICALITY` TEXT NULL,
  `STATUS` TEXT NULL,
  PRIMARY KEY (`ID`));
