CREATE TABLE `HealthPort`.`ALLERGYINTOLERANCE` (
  `ID` VARCHAR(255) NOT NULL,
  `DISPLAY` TEXT NULL,
  `SUBSTANCE` VARCHAR(255) NULL,
  `SUBJECT` TEXT NULL,
  `SENSITIVITY_TYPE` TEXT NULL,
  `RECORDED_DATE` DATE NULL,
  `REACTION` TEXT NULL,
  `CRITICALITY` TEXT NULL,
  `STATUS` TEXT NULL,
  PRIMARY KEY (`ID`));