CREATE TABLE `HealthPort`.`SUBSTANCE` (
  `ID` VARCHAR(255) NOT NULL,
  `NAME` TEXT NULL,
  `TYPE_SYSTEM` TEXT NULL,
  `TYPE_CODE` TEXT NULL,
  `TYPE_DISPLAY` TEXT NULL,
  `EXTENSION_SYSTEM` TEXT NULL,
  `EXTENSION_CODE` TEXT NULL,
  `EXTENSION_DISPLAY` TEXT NULL,
  PRIMARY KEY (`ID`));